ubudget/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users/dashboard', to: 'users#dashboard', as: 'dashboard'
  delete 'users/destroy', to: 'users#destroy', as: 'delete_account'
  get 'users/terms', to: 'users#terms', as: 'terms'
  get 'users/privacy', to: 'users#privacy', as: 'privacy'

  resources :financials
  
  root 'users#index', as: 'home'

end

ubudget/app/models/financial.rb
class Financial < ActiveRecord::Base
	belongs_to :user


	def credits
		total = wage || 0
		total += investments || 0
		total += interest || 0
		total += misc_income || 0
		total += other_income1 || 0
		total += other_income2 || 0
		total += spouse_income || 0
	end


	def credits_to_datum
		# [{"label": "Four", "value" : 196.45946739256}]
		data = []
		data << {label: "Wage", value: wage.to_f}
		data <<	{label: "Investments", value: investments.to_f}
		data << {label: "Interest", value: interest.to_f}
		data << {label: "Misc Income", value: misc_income.to_f}
		data << {label: "Other Income 1", value: other_income1.to_f}
		data << {label: "Other Income 2", value: other_income2.to_f}
		data << {label: "Spouse Income", value: spouse_income.to_f}
	end

	def expenses
		total = rent || 0
		total += home_maintenance || 0
		total += electricity || 0
		total += water || 0
		total += gas_oil || 0
		total += phone || 0
		total += food || 0
		total += insurance || 0
		total += car_payment || 0
		total += gas || 0
		total += car_insurance || 0
		total += credit_cards || 0
		total += student_loan || 0
		total += other_loans || 0
		total += misc_expenses || 0
		total += second_mortgage || 0
		total += auto_repairs || 0
		total += other_auto || 0
		total += dining_out || 0
		total += dental_insurance || 0
		total += home_improvement || 0
		total += dry_cleaning || 0
		total += laundry || 0
		total += childcare || 0
		total += cable || 0
		total += travel || 0
		total += internet || 0
		total += computer_costs || 0
		total += baby_costs || 0
		total += other_expenses1 || 0
		total += other_expenses2 || 0
		total += other_expenses3 || 0
		total += life_insurance || 0
		total += home_insurance || 0
		total += entertainment || 0
	end

	def expenses_to_datum
		# [{"label": "Four", "value" : 196.45946739256}]
		data = []
		data << {label: "Rent", value: rent.to_f}
		data <<	{label: "Home Maintenance", value: home_maintenance.to_f}
		data << {label: "Electricity", value: electricity.to_f}
		data << {label: "Water", value: water.to_f}
		data << {label: "Gas/Oil", value: gas_oil.to_f}
		data << {label: "Phone", value: phone.to_f}
		data << {label: "Food", value: food.to_f}
		data << {label: "Insurance", value: insurance.to_f}
		data << {label: "Car Payment", value: car_payment.to_f}
		data << {label: "Gas", value: gas.to_f}
		data << {label: "Car Insurance", value: car_insurance.to_f}
		data << {label: "Credit Cards", value: credit_cards.to_f}
		data << {label: "Student Loan", value: student_loan.to_f}
		data << {label: "Other Loans", value: other_loans.to_f}
		data << {label: "Misc. Expenses", value: misc_expenses.to_f}
		data << {label: "Second Mortgage", value: second_mortgage.to_f}
		data << {label: "Auto Repairs", value: auto_repairs.to_f}
		data << {label: "Other Auto", value: other_auto.to_f}
		data << {label: "Dining Out", value: dining_out.to_f}
		data << {label: "Dental Insurance", value: dental_insurance.to_f}
		data << {label: "Home Improvement", value: home_improvement.to_f}
		data << {label: "Dry Cleaning", value: dry_cleaning.to_f}
		data << {label: "Laundry", value: laundry.to_f}
		data << {label: "Childcare", value: childcare.to_f}
		data << {label: "Cable", value: cable.to_f}
		data << {label: "Travel", value: travel.to_f}
		data << {label: "Internet", value: internet.to_f}
		data << {label: "Computer Costs", value: computer_costs.to_f}
		data << {label: "Baby Costs", value: baby_costs.to_f}
		data << {label: "Other Expenses 1", value: other_expenses1.to_f}
		data << {label: "Other Expenses 2", value: other_expenses2.to_f}
		data << {label: "Other Expenses 3", value: other_expenses3.to_f}
		data << {label: "Life Insurance", value: life_insurance.to_f}
		data << {label: "Home Insurance", value: home_insurance.to_f}
		data << {label: "Entertainment", value: entertainment.to_f}
	end

	def savings
		total = emergency_savings || 0
		total += college_savings || 0
		total += retirement_savings || 0
		total += other_savings || 0
	end

	def savings_to_datum
		# [{"label": "Four", "value" : 196.45946739256}]
		data = []
		data << {label: "Emergency Savings", value: emergency_savings.to_f}
		data <<	{label: "College Savings", value: college_savings.to_f}
		data << {label: "Retirement Savings", value: retirement_savings.to_f}
		data << {label: "Other Savings", value: other_savings.to_f}
	end

end

ubudget/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :financial, dependent: :destroy

  after_create :make_financial

  def make_financial
  	self.create_financial
  end

end

ubudget/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	  dashboard_path
	end

	
end

ubudget/app/controllers/financials_controller.rb
class FinancialsController < ApplicationController
	before_action :set_financial, only: [:update, :edit]

	def index
		@financials = Financial.all
	end

	def edit
	end

	def new
		@financial = Financial.new
	end

	def update
		@financial.update(financial_params)	
		redirect_to dashboard_path
	end

	private

	def financial_params
		params.require(:financial).permit(:wage,:investments,:interest,:misc_income,:other_income1,:other_income2,:spouse_income,:rent,:home_maintenance,:electricity,:water,:gas_oil,:phone,:food,:insurance,:car_payment,:gas,:car_insurance,:credit_cards,:student_loan,:other_loans,:misc_expenses,:second_mortgage,:auto_repairs,:other_auto,:dining_auto,:dental_insurance,:home_improvement,:dry_cleaning,:laundry,:childcare,:cable,:travel,:internet,:computer_costs,:baby_costs,:other_expenses1,:other_expenses2,:other_expenses3,:life_insurance,:home_insurance,:entertainment,:emergency_savings,:college_savings,:retirement_savings,:other_savings)
	end

	def set_financial
		@financial = Financial.find(params[:id])
	end
	
end

ubudget/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]

	def index
		@users = User.all
	end

	def dashboard
		@financial = current_user.financial
	end

end

ubudget/app/helpers/application_helper.rb
module ApplicationHelper
end

ubudget/app/helpers/financials_helper.rb
module FinancialsHelper
end

ubudget/app/helpers/users_helper.rb
module UsersHelper
end

ubudget/app/views/financials/_credits_graph.html.erb
<div id="financials1"></div>
<script type="text/javascript">
	creditsData = <%= raw @financial.credits_to_datum.to_json if @financial.credits %>;
	nv.addGraph(function() {
 		var chart = nv.models.pieChart()
      .x(function(d) { return d.label })
      .y(function(d) { return d.value })
      .showLabels(false);

    d3.select("#financials1")
    		.append("svg:svg")
        .datum(creditsData)
        .transition().duration(350)
        .call(chart);

  return chart;
	});
</script>

ubudget/app/views/financials/_expenses.html.erb
<div class="container" id="expense_form">
	
	<h1 id="h1-center">Expenses</h1>
	
	<div class="col-md-4">
		 <%= form_for(@financial) do |f| %>
		 	<p>
		 		<%= f.label :rent, "Mortgage/Rent" %><br>
		 		<%= f.text_field :rent, value: @financial.rent || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :second_mortgage, "Second Mortgage" %><br>
		 		<%= f.text_field :second_mortgage, value: @financial.second_mortgage || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :home_maintenance, "Home Maintenance" %><br>
		 		<%= f.text_field :home_maintenance, value: @financial.home_maintenance || 0 %>
		 	</p>
		 	<p>
		 		<%= f.label :home_improvement, "Home Improvement" %><br>
		 		<%= f.text_field :home_improvement, value: @financial.home_improvement|| 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :home_insurance, "Home Insurance" %><br>
		 		<%= f.text_field :home_insurance, value: @financial.home_insurance || 0  %>
		 	</p>	
		 	<p>
		 		<%= f.label :electricity, "Electricity" %><br>
		 		<%= f.text_field :electricity, value: @financial.electricity || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :cable, "Cable" %><br>
		 		<%= f.text_field :cable, value: @financial.cable || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :internet, "Internet" %><br>
		 		<%= f.text_field :internet, value: @financial.internet || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :computer_costs, "Computer Costs" %><br>
		 		<%= f.text_field :computer_costs, value: @financial.computer_costs || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :water, "Water" %><br>
		 		<%= f.text_field :water, value: @financial.water || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :gas_oil, "Gas/Oil" %><br>
		 		<%= f.text_field :gas_oil, value: @financial.gas_oil || 0   %>
		 	</p>
	
		 	<p>
		 		<%= f.label :phone, "Phone" %><br>
		 		<%= f.text_field :phone, value: @financial.phone || 0   %>
		 	</p>	
	</div>
	<div class="col-md-4">		 	
		 <p>
		 		<%= f.label :car_insurance, "Car Insurance" %><br>
		 		<%= f.text_field :car_insurance, value: @financial.car_insurance || 0   %>
		 	</p>
		 	<p>
		 		<%= f.label :car_payment, "Car Payment" %><br>
		 		<%= f.text_field :car_payment, value: @financial.car_payment || 0   %>
		 	</p>
		 	<p>
		 		<%= f.label :gas, "Vehicle Fuel" %><br>
		 		<%= f.text_field :gas, value: @financial.gas || 0   %>
		 	</p>
		 	<p>
		 		<%= f.label :auto_repairs, "Auto Repairs" %><br>
		 		<%= f.text_field :auto_repairs, value: @financial.auto_repairs || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :other_auto, "Other Auto" %><br>
		 		<%= f.text_field :other_auto, value: @financial.other_auto || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :travel, "Travel" %><br>
		 		<%= f.text_field :travel, value: @financial.travel || 0  %>
		 	</p>	 	
		 	<p>
		 		<%= f.label :food, "Food" %><br>
		 		<%= f.text_field :food, value: @financial.food || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :dining_out, "Dining Out" %><br>
		 		<%= f.text_field :dining_out, value: @financial.dining_out || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :dry_cleaning, "Dry Cleaning" %><br>
		 		<%= f.text_field :dry_cleaning, value: @financial.dry_cleaning || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :laundry, "Laundry" %><br>
		 		<%= f.text_field :laundry, value: @financial.laundry || 0  %>
		 	</p>
		 	
		 	<p>
		 		<%= f.label :entertainment, "Entertainment" %><br>
		 		<%= f.text_field :entertainment, value: @financial.entertainment || 0  %>
		 	</p>
		 		
			<p>
		 		<%= f.label :insurance, "Health Insurance" %><br>
		 		<%= f.text_field :insurance, value: @financial.insurance || 0   %>
		 	</p>
	</div>
	<div class="col-md-4">	 	
		 	<p>
		 		<%= f.label :dental_insurance, "Dental Insurance" %><br>
		 		<%= f.text_field :dental_insurance, value: @financial.dental_insurance || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :life_insurance, "Life Insurance" %><br>
		 		<%= f.text_field :life_insurance, value: @financial.life_insurance || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :childcare, "Child Care" %><br>
		 		<%= f.text_field :childcare, value: @financial.childcare || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :baby_costs, "Baby Costs" %><br>
		 		<%= f.text_field :baby_costs, value: @financial.baby_costs || 0  %>
		 	</p>	
		 	<p>
		 		<%= f.label :credit_cards, "Credit Cards" %><br>
		 		<%= f.text_field :credit_cards, value: @financial.credit_cards || 0   %>
		 	</p>
		 	<p>
		 		<%= f.label :student_loan, "Student Loan" %><br>
		 		<%= f.text_field :student_loan, value: @financial.student_loan || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :other_loans, "Other Loans" %><br>
		 		<%= f.text_field :other_loans, value: @financial.other_loans || 0   %>
		 	</p>
		 	 <p>
		 		<%= f.label :misc_expenses, "Misc. Expenses" %><br>
		 		<%= f.text_field :misc_expenses, value: @financial.misc_expenses || 0  %>
		 	</p>	
		 	<p>
		 		<%= f.label :other_expenses1, "Other Expenses 1" %><br>
		 		<%= f.text_field :other_expenses1, value: @financial.other_expenses1 || 0  %>
		 	</p>		 	
		 	<p>
		 		<%= f.label :other_expenses2, "Other Expenses 2" %><br>
		 		<%= f.text_field :other_expenses2, value: @financial.other_expenses2 || 0  %>
		 	</p>	
		 	<p>
		 		<%= f.label :other_expenses3, "Other Expenses 3" %><br>
		 		<%= f.text_field :other_expenses3, value: @financial.other_expenses3 || 0  %>
		 	</p>	
	</div>	 		
		 	<hr>

		 	<p>
		 		Add Expenses:<br>
		 		<%= submit_tag 'Submit' %>
		 	</p>
			<% end %>	
				
</div>

	
			
		 	
		 	
		 	
		 	
		 	

ubudget/app/views/financials/_expenses_graph.html.erb
<div id="financials3"></div>
	<script type="text/javascript">
		expensesData = <%= raw @financial.expenses_to_datum.to_json if @financial.expenses %>;
		nv.addGraph(function() {
	 		var chart = nv.models.pieChart()
	      .x(function(d) { return d.label })
	      .y(function(d) { return d.value })
	      .showLabels(true);

	    d3.select("#financials3")
	    		.append("svg:svg")
	        .datum(expensesData)
	        .transition().duration(350)
	        .call(chart);

	  return chart;
	});
	</script>

ubudget/app/views/financials/_income.html.erb
 <div class="container" id="income_form">
 	
 	<div class="col-md-12">
 		<h1 id="h1-center">Income</h1>
 	</div>
	
	<div class="col-md-6">
	 <%= form_for(@financial) do |f| %>
	 	<p>
	 		<%= f.label :wage, "Income" %><br>
	 		<%= f.text_field :wage, value: @financial.wage || 0  %>
	 	</p>
	 	<p>
	 		<%= f.label :spouse_income, "Spouse's Income" %><br>
	 		<%= f.text_field :spouse_income, value: @financial.spouse_income || 0  %>
	 	</p>
	 	<p>
	 		<%= f.label :interest, "Interest Income" %><br>
	 		<%= f.text_field :interest, value: @financial.interest || 0   %>
	 	</p>
	 	<p>
	 		<%= f.label :investments, "Investment Income" %><br>
	 		<%= f.text_field :investments, value: @financial.investments || 0  %>
	 	</p>
	</div>
	<div class="col-md-6"> 	
	 	<p>
	 		<%= f.label :misc_income, "Miscellaneous Income" %><br>
	 		<%= f.text_field :misc_income, value: @financial.misc_income || 0   %>
	 	</p> 	
	 	<p>
	 		<%= f.label :other_income1, "Other Income 1" %><br>
	 		<%= f.text_field :other_income1, value: @financial.other_income1 || 0  %>
	 	</p>
	 	<p>
	 		<%= f.label :other_income2, "Other Income 2" %><br>
	 		<%= f.text_field :other_income2, value: @financial.other_income2 || 0  %>
	 	</p>	
	 	<hr>	 	
		<p>
			Add Income:<br>
			<%= submit_tag 'Submit' %>
		</p>
		<% end %>
	</div>
	

</div>	

ubudget/app/views/financials/_savings.html.erb
 <div class="container" id="savings_form">
 	
 	<div class="col-md-12">
 		<h1 id="h1-center">Savings</h1>
 	</div>
	
	<div class="col-md-6">
		 <%= form_for(@financial) do |f| %>
		 	<p>
		 		<%= f.label :emergency_savings, "Emergency Savings" %><br>
		 		<%= f.text_field :emergency_savings, value: @financial.emergency_savings || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :college_savings, "College Savings" %><br>
		 		<%= f.text_field :college_savings, value: @financial.college_savings || 0  %>
		 	</p>
	</div>

	<div class="col-md-6">
		 	<p>
		 		<%= f.label :retirement_savings, "Retirement Savings" %><br>
		 		<%= f.text_field :retirement_savings, value: @financial.retirement_savings || 0  %>
		 	</p>
		 	<p>
		 		<%= f.label :other_savings, "Other Savings" %><br>
		 		<%= f.text_field :other_savings, value: @financial.other_savings || 0  %>
		 	</p>
		 	<hr>
			<p>
				Add Savings:<br>
				<%= submit_tag 'Submit' %>
			</p>
		<% end %>
	</div>
	
	
</div>	

ubudget/app/views/financials/_savings_graph.html.erb
<div id="financials2"></div>
	<script type="text/javascript">
		savingsData = <%= raw @financial.savings_to_datum.to_json if @financial.savings %>;
		nv.addGraph(function() {
	 		var chart = nv.models.pieChart()
	      .x(function(d) { return d.label })
	      .y(function(d) { return d.value })
	      .showLabels(false);

	    d3.select("#financials2")
	    		.append("svg:svg")
	        .datum(savingsData)
	        .transition().duration(350)
	        .call(chart);

	  return chart;
	});
</script>

ubudget/app/views/financials/_summary.html.erb
<div class="summary_area">
	<div class="container" id="summary_form">
		<h1 id="h1-center">Summary</h1>
		<h4>Total Surplus: $<%= @financial.credits - @financial.expenses %></h4>
		
		<div class="row" id-"summary-row1">
			<div class="col-md-6" id="summary-income">
				<p>Total income: $<%= @financial.credits %></p>
				<%= render 'financials/credits_graph' %>
			</div>
		
			<div class="col-md-6" id="summary-savings">
				<p>Total savings: $<%= @financial.savings %></p>
				<%= render 'financials/savings_graph' %>
			</div>
		</div>	
		<hr>
		<div class="row">

			<div class="col-md-12" id="summary-expenses">
				<p>Total expenses: $<%= @financial.expenses %></p>
				<%= render 'financials/expenses_graph' %>
			</div>
		</div>	
	</div>
</div>	

ubudget/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubudget</title>
	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="container">
			<div class="col-md-6">
				<% if current_user %>
					<h1 class="animated bounceInDown" id="logo"><%= link_to 'uBudget', dashboard_path %> </h1>
				<% else %>
					<h1 class="animated bounceInDown" id="logo"><%= link_to 'uBudget', home_path %> </h1>
				<% end %>
			</div>
			<div class="col-md-6">
				<nav>
					<% if current_user %>					
						<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
						<li><%= link_to 'Edit Account', edit_user_registration_path(current_user) %></li>
					<% end %>
				</nav>
			</div>	
	  </div>
	</header>

	<%= yield %>

	<footer>
		<div class="container">
			<div class="col-md-6">
				<h2>Company</h2>
				<ul>
					<li><%= link_to 'Terms of Use', terms_path %></li>
					<li><%= link_to 'Privacy Policy', privacy_path %></li>
				</ul>
			</div>
			<div class="col-md-6">
				<h2>Contact Us</h2>
				<ul>		
					<li>New York, NY</li>
					<li><a href="mailto:ngati016@hotmail.com">Send Us An Email!</a></li>
				</ul>
			</div>
	</div>
	</footer>
</body>
</html>

ubudget/app/views/users/dashboard.html.erb
<div class="dashboard">
	
	<div class="container" id="dashboard-area">
		<h4 class='greeting'>Hey, <%= current_user.email %>!</h4>
		
		<div class="col-md-12" id="table">			
			<!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">
			  <li role="presentation" class="active"><a href="#summary" aria-controls="summary" role="tab" data-toggle="tab">Summary</a></li>
			  <li role="presentation"><a href="#income" aria-controls="income" role="tab" data-toggle="tab">Income</a></li>
			  <li role="presentation"><a href="#expenses" aria-controls="expenses" role="tab" data-toggle="tab">Expenses</a></li>
			  <li role="presentation"><a href="#savings" aria-controls="savings" role="tab" data-toggle="tab">Savings</a></li>
			</ul>

			<!-- Tab panes -->
			<div class="tab-content">
			  <div role="tabpanel" class="tab-pane active" id="summary"><%= render 'financials/summary' %></div>
			  <div role="tabpanel" class="tab-pane" id="income"><%= render 'financials/income' %></div>
			  <div role="tabpanel" class="tab-pane" id="expenses"><%= render 'financials/expenses' %></div>
			  <div role="tabpanel" class="tab-pane" id="savings"><%= render 'financials/savings' %></div>
			</div>

		</div>  
	</div>	
	
</div>	

ubudget/app/views/users/index.html.erb
<div class="top-index">
		<div class="index-login">
			<ul>
				<li class="animated bounceInLeft"><%= link_to 'Sign Up!', new_user_registration_path %></li>
				<li class="animated bounceInRight"><%= link_to 'Sign In!',new_user_session_path %></li>
			</ul>
		</div>
		<div class="animated slideInUp" id="short-info">
			<p >uBudget simplifies the budgeting experience!<br>Sign up today and start taking control over your finances.</p>
		</div>
		<%= link_to image_tag('arrow-down1.png', class: 'animated infinite pulse', id: 'arrow1'), "#about"%>
</div>

<div class="about-index" id="about">
	<div class="container">
		<div class="col-md-6">
			<%= link_to image_tag('tree_graph.png', id: 'tree-pic') %>
		</div>
		<div class="col-md-6" id="about-information">
			<h2>About uBudget</h2>
			<p>uBudget is all about simplicity. Our goal is to take the stress out of budgeting. We've used budgeting apps before and have found that they're too robust for the average person. We've decided to create a way to budget for your small expenses so that you don't need to sludge through an owner's manual to figure out your finances. Try out uBudget for free today.</p>
		</div>
	</div>	
</div>